name: Backend CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend:
    name: Backend • Node 20
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12

    env:
      NODE_ENV: test
      MONGO_URI: mongodb://localhost:27017/rxlog_test
      # Add any other test envs your app expects, e.g.:
      # JWT_SECRET: test-secret

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Lint
        working-directory: backend
        run: npm run lint --if-present

      - name: Unit/Integration tests with coverage
        working-directory: backend
        run: |
          npm test --if-present -- --coverage
          if [ -d coverage ]; then tar -czf coverage.tgz coverage; fi

      - name: Upload coverage artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.tgz
          if-no-files-found: ignore
          retention-days: 7

      - name: Build (type-check or compile if TS)
        working-directory: backend
        run: npm run build --if-present
