name: Frontend CI

on:
  push:
    branches: ["**"]
  pull_request:

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  frontend:
    name: Frontend • Node 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Lint
        working-directory: frontend
        run: npm run lint --if-present

      - name: Typecheck
        working-directory: frontend
        run: npm run typecheck --if-present

      - name: Build
        working-directory: frontend
        env:
          # Provide the API base URL used in builds; override in PRs/branches if needed
          VITE_API_BASE_URL: http://localhost:4000
        run: npm run build
